# Introduction to PyTorch
## Tensors

In [7]:
import torch

Construct a 4 x 6 matrix, unitialized. An unitialized matrix is declared, but does not contain definite known values before it is used.

In [8]:
x = torch.empty(4, 6)
x

tensor([[0.0000e+00, 3.6893e+19, 0.0000e+00, 3.6893e+19, 1.4013e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.6893e+19, 0.0000e+00, 3.6893e+19, 1.4013e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

Construct a randomly initialized matrix.

In [10]:
x = torch.rand(4, 6)
x

tensor([[0.9756, 0.6627, 0.3898, 0.1853, 0.5769, 0.0080],
        [0.5120, 0.4157, 0.6853, 0.6397, 0.8311, 0.9389],
        [0.3345, 0.0095, 0.4657, 0.1080, 0.0390, 0.6585],
        [0.8554, 0.0952, 0.6327, 0.0950, 0.0601, 0.2438]])

Construct a matrix of zeros and of dtype long.

In [11]:
x = torch.zeros(4, 6, dtype=torch.long)
x

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

Construct a tensor directly from data.

In [13]:
x = torch.tensor([4.5, 6])
x

tensor([4.5000, 6.0000])

Create a tensor based on an existing tensor.

In [15]:
x = x.new_ones(4, 6, dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0.7211, 0.7685, 0.0872, 0.3211, 0.6933, 0.7115],
        [0.9496, 0.9441, 0.9444, 0.8059, 0.9005, 0.7288],
        [0.0805, 0.8205, 0.2637, 0.4820, 0.7876, 0.8392],
        [0.4908, 0.5050, 0.6951, 0.2741, 0.9375, 0.6088]])


In [16]:
x.size()

torch.Size([4, 6])

## Operations

In [18]:
y = torch.rand(4, 6)
x + y

tensor([[0.8432, 0.8269, 1.0797, 1.2461, 0.8941, 1.0956],
        [1.5322, 1.8784, 1.8285, 1.2201, 1.0275, 1.1845],
        [0.5564, 1.4985, 0.3922, 1.4082, 1.1998, 1.4186],
        [0.7498, 0.9717, 1.5593, 0.2887, 0.9407, 1.5305]])

In [19]:
torch.add(x, y)

tensor([[0.8432, 0.8269, 1.0797, 1.2461, 0.8941, 1.0956],
        [1.5322, 1.8784, 1.8285, 1.2201, 1.0275, 1.1845],
        [0.5564, 1.4985, 0.3922, 1.4082, 1.1998, 1.4186],
        [0.7498, 0.9717, 1.5593, 0.2887, 0.9407, 1.5305]])

Can provide an output tensor as argument

In [20]:
result = torch.empty(4, 6)
torch.add(x, y, out=result)
result

tensor([[0.8432, 0.8269, 1.0797, 1.2461, 0.8941, 1.0956],
        [1.5322, 1.8784, 1.8285, 1.2201, 1.0275, 1.1845],
        [0.5564, 1.4985, 0.3922, 1.4082, 1.1998, 1.4186],
        [0.7498, 0.9717, 1.5593, 0.2887, 0.9407, 1.5305]])

In-place addition

In [21]:
y.add_(x)

tensor([[0.8432, 0.8269, 1.0797, 1.2461, 0.8941, 1.0956],
        [1.5322, 1.8784, 1.8285, 1.2201, 1.0275, 1.1845],
        [0.5564, 1.4985, 0.3922, 1.4082, 1.1998, 1.4186],
        [0.7498, 0.9717, 1.5593, 0.2887, 0.9407, 1.5305]])

NumPy indexing

In [22]:
x[:, 1]

tensor([0.7685, 0.9441, 0.8205, 0.5050])

Resizing a tensor

In [28]:
x = torch.randn(5, 5)
y = x.view(25)
z = x.view(-1, 25) # -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([5, 5]) torch.Size([25]) torch.Size([1, 25])


Use `item()` to get the element from a one-element tensor.

In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0648])
-0.06475076824426651


## Convert a Tensor to a NumPy Array

In [31]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [32]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Convert a NumPy Array to a Tensor
Changing the NumPy array changes the Torch tensor automatically.

In [34]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
